### ISSUE TITLE
Why the WRITE_SECURE_SETTINGS permission must be granted with adb?

### ISSUE THREAD

**Issue by noisemaker00** [TilesOrganization/support#1]
I strongly suggest you to implement this permission grant request into the code, because it is quite complicated for users to grant it with adb.
When I install an app I expect it works 'out-of-the-box'. If I don't have a PC to set up the app in that moment I cannot use it until I perform the adb procedure.
I'm a developer too, if you need help to implement this feature I will give you some hints about that. 
(I used it for my application)

**Comment by rascarlo** [comment]
@noisemaker00 please explain how to enable such permission

**Comment by noisemaker00** [comment]
Sorry, I read page from my smartphone in a hurry and skipped the SECURE word.
So WRITE_SETTINGS can be acquired, WRITE_SECURE_SETTINGS does not, it require the adb commands or root to work properly.
I bought the app by the way. Great work.

**Comment by rascarlo** [comment]
@noisemaker00 thank you for your support
