### ISSUE TITLE
Tasker Intent to Restart Active Tiles

### ISSUE THREAD

**Issue by buffal0b1ll** [TilesOrganization/support#10]
## Feature request i

A tasker intent to Restart Active Tiles would allow substratum users who just applied overlays to quickly create a shortcut they could tap to restart active tiles.

**Comment by rascarlo** [comment]
@buffal0b1ll  What about a tile for it?

**Comment by buffal0b1ll** [comment]
A tile to restart tiles?  That'd work.  A Tasker intent would allow a
profile to force on Monitor Start or make a home screen shortcut.  But a
tile would be a close second.  Optimally the force tiles restart on boot
will work on pixel 2.  I think you mentioned the next release has a fix for
this.


--expect crazy typos--

**Comment by rascarlo** [comment]
Closing issue and labeled as feature added
