### ISSUE TITLE
Sync Now

### ISSUE THREAD

**Issue by thefly1991** [TilesOrganization/support#11]
## Feature request issue

"Sync Now": similar to activate the auto-sync (by pressing once) and disabling late later (by pressing once again), "sync now" only sync everything once and the auto-sync stays off when done (this limits power consumption/data usage). 

The app "Notification Toggle" by j4velin for example has this option (if you need to look at it)
Thanks

**Comment by rascarlo** [comment]
@thefly1991 thanks for opening the issue here with your feature request.

**Comment by rascarlo** [comment]
feature rejected due to the overcomplicated logic to implement such action

**Comment by thefly1991** [comment]
Hi,

Of course it's your choice (and I respect that) but I just find weird to know that the other older app I have on my 5 year old LG G2 has this option (toggle from the notification panel) when 5 years later on my LG G6 I can't have it

So be it.

thanks anyway
