### ISSUE TITLE
No screenshot tile even tho permission has been granted 

### ISSUE THREAD

**Issue by RexenSquared** [TilesOrganization/support#12]
I did adb shell pm grant com.rascarlo.quick.settings.tiles android.permission.WRITE_EXTERNAL_STORAGE in cmd and got no errors but yet I can't add the screenshot tile
![screenshot_2017-12-04-08-19-26](https://user-images.githubusercontent.com/18408903/33554867-58cb86a8-d8cc-11e7-8b91-15101a830867.png)

**Comment by azumukupoe** [comment]
Your device have to be rooted.

**Comment by rascarlo** [comment]
@RealRexen as explained in the google play description, your device needs superuser privileges

**Comment by RexenSquared** [comment]
Then why does the wiki not say that plus there was this other app that could add the screenshot tool without me needing root

**Comment by rascarlo** [comment]
@RealRexen the wiki doesn't say that such command enables the screenshot tile. Also you don't need to use adb to grant external storage permission, because it is listed as a permission that can be requested by the app at runtime. about any other apps doing so, ask to the developers

**Comment by RexenSquared** [comment]
I'll look into the app that I use to use in the past for more quick tiles, this is the app I had used https://play.google.com/store/apps/details?id=it.simonesestito.ntiles but is possible because my phone was made by LG that things could work different? 
Edit: From what I recall the phone didn't use the systems screenshot command but did something that made its own folder and saved the screenshot there

**Comment by rascarlo** [comment]
@RealRexen there is no clean way to take a screenshot on non-rooted devices. Developers can use the MediaProjection class (https://developer.android.com/reference/android/media/projection/MediaProjection.html) but it is a gimmick. such class is intended to use for screenrecording and not to screen capture. I have zero wish and interest in such spaghetti code. I assume they are using the class to start a screenrecord and then extract a frame from the video file. That is a gimmick and Tiles doesn't work on gimmicks or hacky code.

**Comment by RexenSquared** [comment]
So android has a built in screen recorder but no easy screenshot tool (without using the hardware buttons)?

**Comment by rascarlo** [comment]
exactly
