### ISSUE TITLE
[bug] mobile data switch doesn't work properly

### ISSUE THREAD

**Issue by joostk90** [TilesOrganization/support#15]
The icon changes when switches, as does the icon in the top bar (notification panel closed), but in fact data is not switching. It stays active, or when switched off in Android settings, stays off.

I can supply some screenshots to clarify.

OnePlus 5t running Android 7.1.1 and Magisk root.

Cheers!

**Comment by rascarlo** [comment]
@JoostyBoy running stock OnePlus rom?

**Comment by joostk90** [comment]
@rascarlo Yes, that's right. 

```
OnePlus A5010
Android 7.1.1
OxygenOS 4.7.2
Kernel 4.4.21-perf+
```

I just noticed the following. When switching the network traffic state via Tiles, the new state (on/offline) becomes active after accessing the SIM & network menu page in Android settings.

**Comment by joostk90** [comment]
Hereby some screenshots to clarify the issue.

As seen by the icon on the top bar, mobile data is online: 4G+ and arrows left to it.  
![screenshot_20180205-152042](https://user-images.githubusercontent.com/6837764/35848301-ed05a604-0b1d-11e8-8b63-1dee99265377.jpg)

The second tile (from Tiles) to switch the state, here online:  
![screenshot_20180205-152157](https://user-images.githubusercontent.com/6837764/35848302-ed1c337e-0b1d-11e8-94b4-0aa498c7ecd9.jpg)

Here I switched to offline:  
![screenshot_20180205-152202](https://user-images.githubusercontent.com/6837764/35848303-edaf6ebe-0b1d-11e8-8c53-b9e608aef8bd.jpg)

With the notification panel collapsed, part of the icon shows that it is offline (the cross) while the arrows indicate there is still a connection. I can still surf the web.  
![screenshot_20180205-152208](https://user-images.githubusercontent.com/6837764/35848304-edd3aa54-0b1d-11e8-8bbf-13018f04145d.jpg)

The icon remains like that until I open the SIM & network menu. The arrow disappeared:  
![screenshot_20180205-152217](https://user-images.githubusercontent.com/6837764/35848306-ede898d8-0b1d-11e8-8673-cd90325157d0.jpg)

Enabling data again using Tiles:  
![screenshot_20180205-152225](https://user-images.githubusercontent.com/6837764/35848307-edffefce-0b1d-11e8-9637-79c1c702247d.jpg)

Cross disappears, but no 4G+:  
![screenshot_20180205-152228](https://user-images.githubusercontent.com/6837764/35848308-ee186108-0b1d-11e8-84bd-f1e53ea3e825.jpg)

Entering the network menu again and all goes online now:  
![screenshot_20180205-152231](https://user-images.githubusercontent.com/6837764/35848310-ee2e7a9c-0b1d-11e8-8692-1be81e7b838a.jpg)

I can wait as long as I want before entering the menu, nothing happens.

**Comment by gkatev** [comment]
Also not functional in Xiaomi Redmi Note 4X, LineageOS 14.1. Tiles app crashes when using the mobile data toggle functionality

**Comment by rascarlo** [comment]
Such issue has been fixed in the upcoming release. It has been implemented using a simple superuser call. Hence the action to change cellular data will be available only on devices with superuser privileges. Thanks for opening the issue

**Comment by gkatev** [comment]
Hello, I downloaded the new version(2.0.5) and the cellular data tile does switch off the data but it will not turn it on. (I am on lineageOS)
