### ISSUE TITLE
[feature request] Bluetooth Battery Power Tile

### ISSUE THREAD

**Issue by witterally** [TilesOrganization/support#16]
Android O can now display battery power of context Bluetooth devices but you have to go into Settings > Bluetooth to view the percent. A tile would be fantastic.

**Comment by rascarlo** [comment]
Do you mean a tile to constantly show the connected bt device's battery?

**Comment by witterally** [comment]
Yes that's the usage I was looking for. I'm not even sure if it's possible since I haven't seen that available. Just thought I'd check though. Thank you!

**Comment by rascarlo** [comment]
I have to check if it is possible. But having a tile constantly querying for the connected bt device battery would require a foreground running service to properly show the percentage. Is such thing what you are looking for?

**Comment by witterally** [comment]
That's a great point. I hadn't thought about the possible phone battery impacts of a running service and constantly querying the wireless device. 

I wouldn't worry about this, it's not a big deal for the negative impact it might make. Thanks for taking the time to think it over.
