### ISSUE TITLE
[bug] Screenshots make a blank image

### ISSUE THREAD

**Issue by acoustic-git-tar** [TilesOrganization/support#19]
I'm rooted.
Upon clicking the screenshot tile, the notification "Screenshot captured" pops up, but the image enclosed is blank. The image written to storage is also blank. Love your app btw.

**Comment by cpthero** [comment]
Same is happening for me on Android 8.1. No fix after 3 months?

**Comment by rascarlo** [comment]
@sparklightSU @cpthero this is not a bug in Tiles, but a bug with superuser apps.
You can try the following on your android device:
- open a terminal window
- type su (to get superuser privileges)
- type screencap /sdcard/screencap.png
- observe the result.

The image will be blank.
