### ISSUE TITLE
[feature request] Switch data card tile request

### ISSUE THREAD

**Issue by insanityinside** [TilesOrganization/support#21]
Since switching to a custom ROM on my OnePlus 3, I'm missing the "switch data card" tile (to swap the active data connection between the two SIMs in my phone). Would it be possible to implement as a quick tile?

There's an Automate flow here - http://llamalab.com/automate/community/flows/13964 - which I'll get on my phone, and hopefully be able to write up here in steps, which I hope will make things easier to implement for you.

**Comment by rascarlo** [comment]
@insanityinside due to privacy and security reasons, such feature is not achievable by Tiles
