### ISSUE TITLE
[bug] Caffeine tile not working after android 8.1 update

### ISSUE THREAD

**Issue by donportugal** [TilesOrganization/support#22]
After updating the OnePlus 5 to android 8.1 the caffeine tile stopped working, when the device default timeout is reached the screen turn off and the notification is dismissed.

Tried without any luck:
- Disabling Battery Optimization for the Tiles app.
- Uninstalled the app and reinstalling it.
- Disabling and enabling the tile.

The caffeinate app doesnt work either, found working the implementation on the "Nougat / Oreo Quick Settings" App wich uses draw over other apps when this is activated.

**Comment by rascarlo** [comment]
Unfortunately this is happening only on OP devices. There is nothing I can do since it is something related to OP and not the standard android frameworks.
