### ISSUE TITLE
[bug] No po-pup for "Input method" tile

### ISSUE THREAD

**Issue by Flnch** [TilesOrganization/support#25]
I added the "input method" tile and selected the pre-defined option such that the input method po-pup should open. However, this only works if the foreground app is the Tiles app itself. Inside other apps or system text fields pressing the "input method" tile shows no effect. Other tiles are working well.

Rooted Nexus 6, Android 8.1.0 (LineageOS, rooted with Magisk)

**Comment by Flnch** [comment]
Strange, I played with other tiles and now it works perfectly. May this be because I granted some extra permission for the "location" tile?

**Comment by rascarlo** [comment]
@Flnch the permission required for the location tile has nothing to do with the input method tile.

**Comment by Flnch** [comment]
Please reopen the issue.

Now I had time to investigate the issue on a clean Nexus 6 virtual device with Android 8.1. After installation, the "input method" tile only works if the focus is on the Tiles application itself. Otherwise, it does not open the input method list. In logcat it shows
```
2019-05-10 12:04:53.038 1733-2572/system_process W/InputMethodManagerService: Ignoring showInputMethodPickerFromClient of uid 10079: com.android.internal.view.IInputMethodClient$Stub$Proxy@7f5979e
```
[On xda developers](https://www.xda-developers.com/how-to-automatically-change-your-keyboard-on-a-per-app-basis/) they mention you need to grant the WRITE_SECURE_SETTINGS permission for automatically changing the keyboard.

After issuing
```
adb shell pm grant com.rascarlo.quick.settings.tiles android.permission.WRITE_SECURE_SETTINGS
```
it works perfectly, without having the focus on Tiles itself. As you already implemented the "write secure settings permission" dialogue and so forth for the location tile, it should be easily fixable.

**Comment by rascarlo** [comment]
Thank you @Flnch 
I will soon update the app.
Thank you very much for taking the time to report such issue. Precious!
