### ISSUE TITLE
Screenshot not working in android P

### ISSUE THREAD

**Issue by GoukiAkuma** [TilesOrganization/support#27]
## Bug issue
[bug]:
Taking screenshots using tiles from quick settings does not work, only captures a white image.

Other info:
Running Android P (Rooted) on Essential Phone PH-1

**Comment by rascarlo** [comment]
@GoukiAkuma Are you using Magisk?

**Comment by GoukiAkuma** [comment]
Yes, on version 16.7
if u need some sort of log, let me know the required steps and i can send it over to u via email.


EDIT: saw a similar bug reported by another user: https://github.com/TilesOrganization/support/issues/19#issuecomment-409504792

tried the terminal commands u've posted.
terminal showed: "gralloc-mapper is missing" message
hope this helps.

strangely this does not happen on my nexus 6P running lineage os 15.1 (android 8.1, rooted)

**Comment by GoukiAkuma** [comment]
Bug seems to be fixed with the latest magisk (v17. 0)

**Comment by rascarlo** [comment]
@GoukiAkuma yes this is a magisk issue.
