### ISSUE TITLE
UI Freeze

### ISSUE THREAD

**Issue by Enzo88** [TilesOrganization/support#3]
In the last update released in date 27/09/2017, cause on Android 8.0 running on Pixel UI Freeze, and an increasing of the CPU temp.

**Comment by rascarlo** [comment]
@Enzo88 Did you read the full changelog on https://github.com/TilesOrganization/support/wiki/Changelog

**Comment by Enzo88** [comment]
Yes, I've tried also to reinstall the app and use only One tile to control the ringtone, but the issue still the same.

**Comment by rascarlo** [comment]
@Enzo88 Did you reinstall the app without previously deleting the app's data? Because if you did, it is still trying to parse the same data.

**Comment by Enzo88** [comment]
No, firstly I've deleted all data.



Il 28 set 2017 13:49, "rascarlo" <notifications@github.com> ha scritto:

**Comment by rascarlo** [comment]
@Enzo88 gotcha. So only one tile, the ringer mode one, is causing the UI to freeze?

**Comment by rascarlo** [comment]
@Enzo88 can you please with a different tile? Thanks

**Comment by Enzo88** [comment]
I don't know if is releated to this specific tile, I've tried with this,
but Can also affect other tiles, if is useful I Can have a try with another
tile.

Il 28 set 2017 13:52, "rascarlo" <notifications@github.com> ha scritto:

**Comment by Enzo88** [comment]
After the last update the issue seem solved. Thanks

**Comment by rascarlo** [comment]
@Enzo88 Thanks for your help. Closing the issue. Thanks again
