### ISSUE TITLE
[feature request] USB Tethering

### ISSUE THREAD

**Issue by snug** [TilesOrganization/support#30]
Hello, I was wondering if it was possible to add a tile for USB tethering.

My request is different to #14, as I'd just like it to toggle the setting on in the same way that USB tethering currently works, ie. temporarily enabled until connection / disconnection. I don't believe this should be a security concern if implemented in the same way.

I use USB tethering for work (and play) a lot, so a tile like this would be very helpful!

**Comment by rascarlo** [comment]
@snug USB tethering is not available to thirdparty applications being a very sensible android feature.
