### ISSUE TITLE
[feature request] screenshot tile

### ISSUE THREAD

**Issue by kps619** [TilesOrganization/support#32]
Could you create a screenshot tile?

Edit: okay, according to the wiki, there is a screenshot tile, but I don't see it as an option in my Tiles app.

**Comment by rascarlo** [comment]
A screenshot tile is already available but only on devices with superuser privileges

**Comment by rascarlo** [comment]
@kps619 release 2.1 comes with an option to use android accessibility service to take a screenshot on device API 28 and up
