### ISSUE TITLE
[feature request] add settings shortcut to changing default payment app

### ISSUE THREAD

**Issue by revanmj** [TilesOrganization/support#34]
As title says, would it be possible to add settings shortcut to the screen where you can change default payment (HCE) app? (Google Pay or your bank's app)

I know it's reachable from other apps as I successfully created such shortcut with Nova (using activity browser).

**Comment by rascarlo** [comment]
Did you try using an activity tile?

**Comment by revanmj** [comment]
Yes, it works this way, but there are lots of activities there to search from (and no way to quickly filter them), so I thought it would be good idea to add this permanently into settings shortcuts list (icon would also more appropriate).

**Comment by rascarlo** [comment]
Yes I understand but I believe that a specific tile just for that would be redundant and unnecessary. Even more, the app will need first to check how many payment options are available and then show the tile. And such logic could be extremely prone to bugs. I hope it makes sense.
Thanks for your feedback, maybe I should just implement a search view to filter the activities. 
Thanks foe opening the issue.

**Comment by revanmj** [comment]
I didn't mean specific tile - I mean adding payment settings to the list of settings shortcuts inside the app that you can use for settings shortcuts tile.
