### ISSUE TITLE
[bug] Mono-audio toggle does not work on Samsung devices

### ISSUE THREAD

**Issue by EmbersArc** [TilesOrganization/support#36]
It shows up and can be toggled no problem. But it does not actually affect mono audio on my Samsung Galaxy S8 with Android 9. It seems that that setting has to be accessed differently on Samsung phones. A fix, if possible, would be greatly appreciated.

**Comment by rascarlo** [comment]
Hi @EmbersArc is such issue still reproducible?

**Comment by EmbersArc** [comment]
I just tried it and the issue still exists on my S8 with Android 9. It seems that Samsung handles the mono-audio setting differently. Let me know what other information you need to help fix it.

**Comment by rascarlo** [comment]
@EmbersArc was such issue present also on Android 8?

**Comment by EmbersArc** [comment]
Yes it was also present on Android 8.

**Comment by rascarlo** [comment]
Then I believe that samsung is overriding the AOSP behaviour for mono-audio and without looking at the source code I have no way to properly debug the issue and find a solution. Where is the mono-audio found on samsung devices?

**Comment by EmbersArc** [comment]
In Samsung devices it's under `Settings` > `Accessibility` > `Hearing enhancements` > `Mono audio`.

Unfortunately I couldn't find an activity to access it directly.  Although `Hearing enhancements` can be opened with `.Activities$AccessibilitySettingsHearingActivity`
