### ISSUE TITLE
[bug] storage tile open file manager not working Android 10

### ISSUE THREAD

**Issue by caeldom** [TilesOrganization/support#38]
Storage Tile
Action set to open file manager, pressing tile and file manager does not open. Android 10 probably changed something.

**Comment by rascarlo** [comment]
@caeldom release 2.1 has a fix for it. closing the issue

**Comment by caeldom** [comment]
Updated to 2.1, still having issue though. Specifically when Action is set to Open File Manager.

**Comment by rascarlo** [comment]
Hi, what device are you using?

**Comment by caeldom** [comment]
> Hi, what device are you using?

Google Pixel 3a
