### ISSUE TITLE
[Bug] Tiles switch issue on Android 10

### ISSUE THREAD

**Issue by TragicLifeHu** [TilesOrganization/support#39]
*I am NOT a native English speaker, so sorry if my description is unclear

System: Android 10 aarch64 AOSP
SU: Magisk 20.1
Issue: Sometimes I toggle on a tile but the command it works is toggle off
This really confused me
Only by restarting the phone could fix this issue, but soon it reproduced again
I noticed that before this issue happens, I will have an operation (a toggle in system tile menu) invalid first

I think it is about the backgroud services of app, but my phone does not even have a background app limitation.

**Comment by rascarlo** [comment]
@TragicLifeHu can you tell what device are you using and what tiles you are referring to?

**Comment by TragicLifeHu** [comment]
@rascarlo My device is ZUK Z2 Plus with SD820. This is a universal issue and happens on any tile

**Comment by rascarlo** [comment]
@TragicLifeHu I believe this is something due to the Lenovo very aggressive doze: https://dontkillmyapp.com/lenovo

**Comment by TragicLifeHu** [comment]
@rascarlo I have flashed AOSP, so I think it is not related to the manufacturer
This bug appears even I have not screen off for bootup

**Comment by rascarlo** [comment]
Did you flash aosp on a lenovo device?  How so?

**Comment by TragicLifeHu** [comment]
ZUK series are open source. And Lenovo dropped all ZUKs in 2018, so there's no more further support from Lenovo.
