### ISSUE TITLE
Support the ability to run an action inside an application

### ISSUE THREAD

**Issue by digiguru** [TilesOrganization/support#4]
I like the ability in Tasker to be able to run an action in an application, specifically in pocketcasts I can do this:

http://support.pocketcasts.com/article/third-party-integration/

Is it possible to be able to trigger actions from a tile?

Many thanks

**Comment by rascarlo** [comment]
@digiguru I don't use tasker so that I may not be of much help, but I guess you can use the shortcut to trigger tasker. That's what some are doing I believe

**Comment by rascarlo** [comment]
@digiguru you can also use the new activity tile and check if the application exposes any activity for your desired action and add it to the tile.
I am closing this issue because it is not something that Tiles points to achieve nor targets.
Thank you for submitting your issue.
