### ISSUE TITLE
[Bug] Tile Invert colors swaps its state icons on Android 10

### ISSUE THREAD

**Issue by jise** [TilesOrganization/support#40]
I was wondering whether to continue with issue #39, but in the end I'm starting new one because there are some differences. On my device not all tiles are affected but only this one. TBH I added so far with Tiles app just five tiles: Applications, Clipboard, Immersive mode, Invert colors and Sleep and the other tiles behave normally.

My device: Asus ZenFone 6 (ZS630KL) with Android 10 Version WW-17.1810.1910.68
App Tiles: all permissions granted (no root, just adb)

Default state after enabling and adding the tile Invert colors:
Normal colors state icon - strikethrough drop in gray
![Screenshot_20191123-093924306-01](https://user-images.githubusercontent.com/6588902/69486865-f0e60380-0e50-11ea-9837-daa31b446269.png)

Invert colors state icon - drop in blue color
![Screenshot_20191123-093938819-01](https://user-images.githubusercontent.com/6588902/69486870-21c63880-0e51-11ea-8aff-90c395a6df2e.png)

Functional test: Tile Invert colors works as it should.

How to trigger this issue:
Open the quick settings, enter quick settings editing layout, close quick settings editing layout.
Yes, even without changing anything, this procedure will trigger the issue.
But of course the same issue will be caused by changing any other tile or adding another tile.

Functional test: After the first use of the tile Invert colors, their state icons are swapped.

How to fix this error (it is a temporary workaround till the next tiles change):
Open the quick settings, enter quick settings editing layout, drag the tile Invert colors down to the tiles repository, drag the tile Invert colors up to the desired position again, close quick settings editing layout.

Functional test: Tile Invert colors works as it should.

**Comment by jise** [comment]
> My device: Asus ZenFone 6 (ZS630KL) with Android 10 Version WW-17.1810.1910.68
> App Tiles: all permissions granted (no root, just adb)

I updated my phone on November 27 to version WW_17.1810.1910.73 via local full update (not OTA), this issue persists.

**Comment by rascarlo** [comment]
@jise  Are you use any power saving app? Maybe it is your device aggressive doze killing the services.
Did you try: https://dontkillmyapp.com/asus

**Comment by jise** [comment]
No, I even excluded Tiles from battery optimization since installation.
I don't use Asus PowerMaster.
As I said I have no problems with other enabled tiles.

**Comment by rascarlo** [comment]
That is so discouraging, because I can not reproduce such issue on my pixel2, on a couple of nokias and all the supported emulators. Even more, you are the first one so far to report such issue with the invert colors tile. I have no clue to be honest

**Comment by rascarlo** [comment]
@jise I am sorry but I have no idea how to fix it. The invert colors tile works by the same logic of many other tiles that reflect any on/off state and I rechecked the code multiple times and there are no bugs. It is extremely heart breaking to not be able to fix such issue. Please if you want a refund, contact me in private and I can issue your refund

**Comment by jise** [comment]
No refund is needed :)
Your app deserve it and I like it a lot.

My issue description is accurate and completely reproducible on my device. Unfortunately, I don't have any other Android 10 device to test it elsewhere.

If I find something, or I think something else I write here, please do not close.

If you would like to try the debug version on my device I am willing to do so.

**Comment by jise** [comment]
> The invert colors tile works by the same logic of many other tiles that reflect any on/off state 

Let know which tiles has the same logic behind, I'll test them too.

**Comment by rascarlo** [comment]
- adaptive brightness
- always on- ambient display- awake while plugged in
- battery saver
- bluetooth
- brightness
- cellular data
- data roaming
- demo mode
- double tap to check
- font size
- heads up notification
- immersive mode
- invert colors
- lift to check- location
- media volume
- monochromacy
- orientation lock
- ringer mode
- sleep timeout
- usb debugging
- touch sounds
- vibrate for calls
- vibrate on tap
