### ISSUE TITLE
Location permission on Q

### ISSUE THREAD

**Issue by WhiCCX0** [TilesOrganization/support#41]
## Bug issue
To create a new issue for a bug, please use the following form:

`[bug] short description of the bug`
Because the new method of location permission on Q that only allow location permission when app tiles is open, so the tiles of location or weather cannot get the location to function correctly. 
___

## Feature request issue

To create a new issue for a bug, please use the following form:

`[feature request] short description of the feature`

**Comment by rascarlo** [comment]
Android deprecated the awareness api: https://developers.google.com/awareness/android-api/snapshot-api-overview
This is why the tiles don't work.
They will be removed in the upcoming release

**Comment by rascarlo** [comment]
@WhiCCX0 actually, you are right. The streetview and map tiles needs access to location in the background to work properly. I have already fixed such issue and it will be available in the upcoming release. Unfortunately the weather tile will be removed being now deprecated.
Thanks for opening this issue and sorry for the inconvenience.

**Comment by WhiCCX0** [comment]
You are welcome 😊.
