### ISSUE TITLE
[Bug] Aod tile not working on Google Pixel 3a with Android 10

### ISSUE THREAD

**Issue by badener95** [TilesOrganization/support#42]
The title pretty much says it all. The tile to toggle always on display does nothing on my Pixel 3a with Android 10.

**Comment by rascarlo** [comment]
@badener95 is the issue fixed on your pixel? Is this way you closed the issue?

**Comment by badener95** [comment]
It seems to work now. I don't know if it has anything to do with the March system update I have installed yesterday and I can't tell you how to replicate the issue I had 2 weeks ago when I have opened this because I did not take logs (shame on me).
