### ISSUE TITLE
[feature request] turn camera flash notifications on or off

### ISSUE THREAD

**Issue by deppi0** [TilesOrganization/support#44]
There is a tile that bring to the menu for the flash notifications but it would be great to have one that turns the camera flash notifications on and off directly. 
Thanks

**Comment by rascarlo** [comment]
What does it mean flash notifications?
And what do you mean with the camera flash notifications?

**Comment by deppi0** [comment]
Hi there.
I attach a screenshot to show you what I am talking about.
Please let me know if it makes sense.
Great app you have set up!

Best

Edmondo

**Comment by rascarlo** [comment]
I don't see any screenshot...

**Comment by deppi0** [comment]
This is weird.
Does it work this time?
Thanks

**Comment by rascarlo** [comment]
No it doesn't

**Comment by deppi0** [comment]
I don't understand...it shows on my sent emails.
[image: Screenshot_20200414-225308_Accessibility.jpg]

**Comment by rascarlo** [comment]
That is not how it works on github. you can check for yourself: https://github.com/TilesOrganization/support/issues/44
