### ISSUE TITLE
[bug] No alarm set issue

### ISSUE THREAD

**Issue by Dre-OS** [TilesOrganization/support#45]
Its supposed to tell if an alarm is set but the tile displays "No Alarm Set" and does not tell the time that the alarm will go off, 

Running Realme 5 on ColorOS 6.0.1 over Android 9

**Comment by rascarlo** [comment]
Did you try to exclude Tiles from battery optimization? this looks like a frequent issue on such vendor due to very aggresive doze

**Comment by Dre-OS** [comment]
I did exempt tiles from battery optimization

**Comment by rascarlo** [comment]
Do any other tile work fine?

**Comment by Dre-OS** [comment]
The media volume tile slider cannot move unless i tap the + or - buttons in the window and counter tile does not register additions that i make on the tile but it work on subraction.

**Comment by Dre-OS** [comment]
After updating to RealmeUI 1.0 (Android 10), the alarm tile shows the time it will go off and can set an alarm but:
- the screen timeout tile cannot change the timeout value, it reverts to the default value after i try to change it.
- the other tiles i mentioned before except the alarm tile, their bug still persist after the update.

**Comment by rascarlo** [comment]
Sorry but those bugs have been introduces by the OS update. Tiles is built against AOSP and its standard features, if vendors decide to override such standards funcionalities, there is nothing I can do to fix their mess
