### ISSUE TITLE
[feature request] Hey google hotword toggle tile

### ISSUE THREAD

**Issue by Dre-OS** [TilesOrganization/support#48]
When "hey google" function of google assistant running in the background, it is quite battery draining when left turned on for quite sometime even if it only functions while the screen is on. Moreover, some use it frequently but would like to preserve battery for other purposes. This can be solved by implementing a toggle tile for that function.

**Comment by rascarlo** [comment]
Unfortunately such thing is not achievable by third party app beside launchers because google does not expose any api for it
