### ISSUE TITLE
Camera Lock

### ISSUE THREAD

**Issue by Sudrien** [TilesOrganization/support#5]
I see Tiles already has a Device Administrator option.

Would there be any possibility of a toggle based on setCameraDisabled() ? That is, when the camera is disabled, apps are blocked from accessing the camera.

https://github.com/jurijalbegger/camerablocker is a sample ui-heavy app with this functionality.

**Comment by rascarlo** [comment]
@Sudrien That is such a nice idea! Let me work on it

**Comment by rascarlo** [comment]
@Sudrien closing the issue. Camera lock tile is available starting version 2.0.2.
Thanks again for your suggestion.
