### ISSUE TITLE
NFC tile just stopped working after a reboot

### ISSUE THREAD

**Issue by ryran** [TilesOrganization/support#9]
![screenshot_20171012-113614](https://user-images.githubusercontent.com/1092618/31507923-1028525e-af42-11e7-97d3-385809a7d3e9.png)

Very weird.... I've already tried triggering a manual force-restart of active tiles.

**Comment by rascarlo** [comment]
@ryran Hi and thanks for opening this issue. Are you on a Nexus 6P?

**Comment by ryran** [comment]
5x actually. However, I spoke too soon because I was able to fix it by hiding/disabling the tile and then re-enabling and re-adding it. Odd. Thanks for the quick response tho!

**Comment by rascarlo** [comment]
@ryran Thanks!
